AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - "lib/bitwise_attributes/active_record_extension.rb"
    - "spec/**/*"

Metrics/ModuleLength:
  Exclude:
    - "lib/bitwise_attributes/active_record_extension.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "lib/bitwise_attributes/active_record_extension.rb"

Metrics/MethodLength:
  Exclude:
    - "lib/bitwise_attributes/active_record_extension.rb"

Metrics/AbcSize:
  Exclude:
    - "lib/bitwise_attributes/active_record_extension.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/bitwise_attributes/active_record_extension.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/bitwise_attributes/active_record_extension.rb"
